config/routes.rb
Rails.application.routes.draw do

	root :to => 'books#index'
 
    


  resources :books
   
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  



  #get 'books#get_files'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end


#rails g scaffold nametable atribs

app/models/book.rb
class Book < ApplicationRecord
	#attr_accesible :name_book, :author_name, :date_created, :editorial, :price

end


#background-image: url(libros-portada.jpg);

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
skip_forgery_protection

  before_action :set_book, only: [:show, :edit, :update, :destroy]
  def get_files
    @books = Book.all

  end
  # GET /books
  #GET /books.json
  def index
    @books = Book.all

  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
   
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
        #format.json { render json:@book,status:ok}

      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)

       
        format.json { render :show, status: :ok, location: @book }
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        
        
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name_book, :author_name, :date_created, :editorial, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :name_book %>
    <%= form.text_field :name_book %>
    
     
    
  </div>

  <div class="field">

    <%= form.label :author_name %>
    <%= form.text_field :author_name %>
  </div>

  <div class="field">
    <%= form.label :date_created %>
    <%= form.date_select :date_created %>
  </div>

  <div class="field">
    <%= form.label :editorial %>
    <%= form.text_field :editorial %>
  </div>

  <div class="field">
    
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>


<h1><%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %></h1>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name book</th>
      <th>Author name</th>
      <th>Date created</th>
      <th>Editorial</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name_book %></td>
        <td><%= book.author_name %></td>
        <td><%= book.date_created %></td>
        <td><%= book.editorial %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1><%= link_to 'New Book', new_book_path %></h1>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<h1><%= link_to 'Back', books_path %></h1>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>


  <p>
  <strong>Name book:</strong>
  <%= @book.name_book %>
  </p>

  <p>
  <strong>Author name:</strong>
  <%= @book.author_name %>
  </p>

  <p>
  <strong>Date created:</strong>
  <%= @book.date_created %>
  </p>

  <p>
  <strong>Editorial:</strong>
  <%= @book.editorial %>
  </p>

  <p>
  <strong>Price:</strong>
  <%= @book.price %>
  </p>

<h1><%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>